### ISSUE TITLE
สรุป meeting #1

### ISSUE THREAD

**Issue by Jiraplus123** [Jiraplus123/WannaBeBillionaires#33]

**Comment by Jiraplus123** [comment]
1.assignงานให้เพื่อนๆทุกคน 
2.draft ตัวที่จะส่งงาน
3.journey map เสร็จแล้ว
4.Think-feel เสร็จแล้ว
5.What how why เสร็จแล้ว
6.เหลือ pov, feedback, ตกแต่ง
7.นัดทำงานวันต่อไปเวลา ทุ่ม-3ทุ่ม

**Comment by Sitthata** [comment]
รับทราบครับผม
